Added About page with lorem ipsum text
pulibrary/pdc_discovery pull request #109
Opened 2021-12-03 16:11 UTC by hectorcorrea

Fixes #82

![about](https://user-images.githubusercontent.com/568286/144634845-df6ca283-6364-461c-a990-e5709c47918b.png)

2021-12-03 16:14 UTC, bess requested changes
@hectorcorrea Looks great, but can we add a simple test here, to ensure it doesn't break with later changes?

2021-12-03 16:17 UTC, kelynch approved these changes

2021-12-03 16:18 UTC, kelynch reviewed
Sorry, accidentally hit "Approve."  Looks good and agree with the above change request from Bess.

2021-12-03 16:31 UTC, hectorcorrea commented
@bess I have added a simple test.

2021-12-07 15:15 UTC, kelynch approved these changes

2021-12-07 15:15 UTC, merged