Adding rake task to create nam synonym file
pulibrary/pdc_discovery pull request #305
Opened 2022-06-29 11:35 UTC by carolyncole

Also move name synonyms to a separate file.

refs #297.  Need to create a PR for pul_solr to close the ticket.

2022-06-29 12:39 UTC, bess requested changes
@carolyncole The logic here looks fine, but I would much prefer to see it in a class instead of a rake task so it can be tested. On slack you mentioned your own misgivings that having this code just in a rake file might not serve us well long-term, and I agree. How would you feel about refactoring this a bit, to move the logic into a class where it can easily be tested, and then the rake task can just invoke it? 

For example, I like the way @kelynch did this PR: https://github.com/pulibrary/pdc_describe/pull/168/files

2022-06-30 13:45 UTC, hectorcorrea commented on spec/models/name_synonym_spec.rb
> +    it 'builds the synonum file' do
synonym

2022-06-30 15:05 UTC, bess approved these changes
🚀

2022-06-30 15:06 UTC, bess approved these changes

2022-06-30 15:21 UTC, bess approved these changes

2022-06-30 15:29 UTC, merged