Fix error in github pages publication pipeline
pulibrary/pdc_discovery pull request #637
Opened 2024-06-28 13:47 UTC by bess

Also, remove an unused stray file

2024-07-01 14:24 UTC, carolyncole requested changes
@bess if the changes to remove tool versions are required then we need to make sure everyone is utilizing the tool versioning software you are utilizing that doe snot use that file.

2024-07-01 14:24 UTC, carolyncole commented on .tool_versions
@bess is this required?  I utilize this file with asdf, so I will not be in sync with the versions.  What file now shows the tool versions?

2024-07-10 20:39 UTC, bess commented on .tool_versions
@carolyncole Sorry, I should have explained why I removed this file. This project, for some reason, has a `.tool_versions` file (note the underscore), in addition to the `.tool-versions` file (note the dash). This PR removes only the file with the underscore, which I think must have been added by mistake at some point.

2024-07-11 11:05 UTC, carolyncole commented on .tool_versions
Thanks!  I missed the _ vs -

2024-07-11 11:05 UTC, carolyncole approved these changes

2024-07-11 11:05 UTC, merged